<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="AFSWWI9CYZ2H4A" failures="1" tests="36" name="Default test" time="12.906" errors="0" timestamp="2023-01-26T10:01:18 CST">
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldDeleteAUser" time="0.052"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldFindAllUsers" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldFindUserByEmail" time="0.006"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldFindUserById" time="0.005"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldSaveAUser" time="0.016"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldThrowNotFoundExceptionIfUserByEmailNotExists" time="0.002">
    <failure type="org.testng.TestException" message="
Method UserServiceTest.shouldThrowNotFoundExceptionIfUserByEmailNotExists()[pri:0, instance:com.developerscorner.provider.service.UserServiceTest@66236a0a] should have thrown an exception of type class com.developerscorner.provider.exception.NotFoundException">
      <![CDATA[org.testng.TestException: 
Method UserServiceTest.shouldThrowNotFoundExceptionIfUserByEmailNotExists()[pri:0, instance:com.developerscorner.provider.service.UserServiceTest@66236a0a] should have thrown an exception of type class com.developerscorner.provider.exception.NotFoundException
at org.testng.internal.ExpectedExceptionsHolder.noException(ExpectedExceptionsHolder.java:82)
at org.testng.internal.TestInvoker.considerExceptions(TestInvoker.java:749)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:634)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- shouldThrowNotFoundExceptionIfUserByEmailNotExists -->
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldThrowNotFoundExceptionIfUserByIdNotExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.UserServiceTest" name="shouldUpdateAUser" time="0.005"/>
  <testcase classname="com.developerscorner.provider.ProviderApplicationTests" name="contextLoads" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.AuthServiceTest" name="shouldAuthenticateAUser" time="0.009"/>
  <testcase classname="com.developerscorner.provider.service.AuthServiceTest" name="shouldRegisterAUser" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.AuthServiceTest" name="shouldThrowConflictExceptionIfUserExists" time="0.003"/>
  <testcase classname="com.developerscorner.provider.service.AuthServiceTest" name="shouldThrowUsernameNotFoundExceptionIfUserNotExists" time="0.004"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldDeleteAQuestion" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldFindAllQuestions" time="0.001"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldFindQuestionById" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldFindQuestionByUserId" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldFindQuestionByUsername" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldSaveAQuestion" time="0.004"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldThrowNotFoundExceptionIfNoQuestionsExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldThrowNotFoundExceptionIfQuestionByIdNotExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldThrowNotFoundExceptionIfQuestionByUserIdNotExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldThrowNotFoundExceptionIfQuestionByUsernameNotExists" time="0.001"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldThrowNotFoundExceptionSavingAQuestionIfUserNotExists" time="0.003"/>
  <testcase classname="com.developerscorner.provider.service.QuestionServiceTest" name="shouldUpdateAQuestion" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldCountNewMessages" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldFindChatMessageById" time="0.003"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldFindChatMessageByReceiver" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldFindChatMessageBySender" time="0.003"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldFindChatMessages" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldFindChatMessagesBySenderAndReceiver" time="0.003"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldSaveChatMessage" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldThrowNotFoundExceptionIfByIdNotExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldThrowNotFoundExceptionIfByReceiverNotExists" time="0.001"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldThrowNotFoundExceptionIfBySenderNotExists" time="0.002"/>
  <testcase classname="com.developerscorner.provider.service.ChatMessageServiceTest" name="shouldUpdateStatuses" time="0.003"/>
</testsuite> <!-- Default test -->
